# name: 'Deploy'
# on:
#   push:
#     branches:
#       - main
#     paths:
#       - 'core/**'
# jobs:
#   gh-pages:
#     concurrency: ci-${{ github.ref }}
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout
#         uses: actions/checkout@v2
#       - name: Install and Build
#         run: |
#           npm ci
#           npm run build -w tokens
#           npm run build:ci -w core
#       - name: Find and Replace
#         uses: jacobtomlinson/gha-find-replace@v2
#         with:
#           find: '/build/'
#           replace: 'https://haiilo.github.io/catalyst/build/'
#           regex: false
#           include: core/www/index.html
#       - name: Deploy
#         uses: JamesIves/github-pages-deploy-action@v4.2.3
#         with:
#           branch: gh-pages
#           folder: core/www
